portainer:
  restart: always
  container_name: portainer.io
  command: --admin-password '<%admin-passpwd-hash%>'
  image: portainer/portainer:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9000:9000"
