#https://media.readthedocs.org/pdf/portainer/latest/portainer.pdf
#https://qnap-dev.github.io/container-station-api/dqpkg.html#other-files-under-shared
portainer:
  restart: always
  container_name: Portainer.io
  command: --admin-password '<@admin_passpwd_hash@>'
  image: portainer/portainer:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9000:9000"
